src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity(fields: ['title'], message: 'Ce trick existe déjà')]
class Trick
{
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable('now');
        $this->updatedAt = new \DateTimeImmutable('now');
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Image::class, orphanRemoval: true)]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class,  orphanRemoval: true)]
    private Collection $videos;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class)]
    private Collection $comments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */

    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTrick($this);
        }
        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {

            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {

            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }
        return $this;
    }

    public function getFirstImage(): ?Image
    {
        return $this->images->first() ?: null;
    }

    public function getFirstVideo(): ?Video
    {
        return $this->videos->first() ?: null;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {

            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }
        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'title',
            ],
            )
            ->add('slug', TextType::class, [
                'label' => 'slug'])
            ->add('category', EntityType::class, [
                    'label' => 'category',
                    'class' => Category::class
                ]
            )
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'tinymce'
                ]
            ])
            ->add('enregistrer', SubmitType::class, [
                'attr' => ['class' => 'btn btn-primary'],
                'label' => 'Enregistrer',
                'row_attr' => ['class' => 'd-grid']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;


use App\Entity\Trick;
use App\Form\TrickType;
use App\Repository\TrickRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\AsciiSlugger;


#[Route('/trick')]
class TrickController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private TrickRepository $trickRepository;
    private PaginatorInterface $paginator;
    private RequestStack $request;


    public function __construct(EntityManagerInterface $entityManager, TrickRepository $trickRepository, PaginatorInterface $paginator, RequestStack $request )
    {
        $this->entityManager = $entityManager;
        $this->trickRepository = $trickRepository;
        $this->paginator = $paginator;
        $this->request = $request;
    }

    #[Route('/{page<\d+>?1}', name: 'app_trick', methods: ['GET'])]
    public function index(): Response
    {
        $tricks = $this->entityManager->getRepository(Trick::class)->findAll();

        return $this->render('trick/index.html.twig', [
            'tricks' => $tricks,
            'user'=> $this->getUser() ? $this->getUser() : null
        ]);
    }

    #[Route('/new', name: 'app_trick_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $trick->setUser($this->getUser());
            $trick = $form->getData();
            $this->entityManager->persist($trick);
            $this->entityManager->flush();
            $this->addFlash('success', 'Nouveau trick a été ajouté avec succès!');
        return $this->redirectToRoute('app_add_image_to_trick', [
            'slug' => $trick->getSlug()]);
    }
        return $this->render('trick/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{slug}/show', name: 'app_trick_show', methods: ['GET'])]
    public function show(Trick $trick, Request $request): Response
    {
        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'request' =>$request
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_trick_edit')]
    public function edit(Request $request, string $slug): Response
    {
        $trick = $this->trickRepository->findOneBy(['slug' => $slug]);
        if ($trick === null) {
            throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException('Impossible de trouver ce trick');
        }
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $trick = $form->getData();
            $slugger = new AsciiSlugger();
            $slug = $slugger->slug($trick->getSlug());
            $trick->setSlug($slug);
            $this->entityManager->persist($trick);
            $this->entityManager->flush();
            $this->addFlash('success', "Modifications enregistrées avec succès!");
            return $this->redirectToRoute('app_edit_image_to_trick', ['slug' => $trick->getSlug()]);
        }
        return $this->renderForm('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}/delete', name: 'app_trick_delete')]
    public function delete(Trick $trick): Response
    {

        $this->entityManager->remove($trick);
        $this->entityManager->flush();

        $this->addFlash('success', "Le Trick a été supprimé avec succès!");
        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }

}

templates/trick/_delete_form.html.twig
<a href="{{ path('app_trick_delete', {'slug': trick.slug }) }}"
   class="btn btn-sm btn-outline-warning border border-info border-3"><img
            src="{{ asset('assets/images/logoDelete.png') }}" height="18px"
            alt="Supprimer trick"></a>

templates/trick/_form.html.twig
<section class="container-fluid background-layout-stairs">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card shadow-lg rounded my-5">
                <div class="jumbotron vh-100card-img-top">
                    <div class="p-1 p-md-4 mb-2 text-white rounded">
                        <div class="row justify-content-center">
                            {{ form_start(form) }}
                            <div class="d-flex justify-content-center align-items-center mt-3">
                            </div>
                            <p class="text-primary fw-bold text-decoration-underline"> Titre :</p>
                            {{ form_row(form.title,{'attr': {'placeholder':'Nom du trick', 'class':'fw-bold mb-4'}}) }}
                            <br>
                            <p class="text-primary fw-bold text-decoration-underline"> Slug :</p>
                            {{ form_row(form.slug,{'attr': {'placeholder':'Slug', 'class':'fw-bold mb-4'}}) }}
                            <br>
                            <p class="text-primary fw-bold text-decoration-underline"> Category :</p>
                            {{ form_row(form.category,{'attr': {'placeholder':'Slug', 'class':'fw-bold mb-4'}}) }}
                            <br>
                            <p class="text-primary fw-bold text-decoration-underline"> Description :</p>
                            {{ form_row(form.description,{'attr':{ 'placeholder':'Description', 'class':'fw-bold mb-4', 'rows':8}}) }}
                            <br>
                        </div>
                        {{ form_end(form) }}
                        <div class="d-flex justify-content-center align-items-center mt-3">
                            <a href="{{ path('app_trick') }}"
                               class="btn btn-sm btn-outline-warning border border-info border-3 text-dark fw-bold"><img
                                        src="{{ asset('assets/images/logoReturn.png') }}" height="18px"
                                        alt="Return"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block album %}{% endblock %}

{% block title %}Modifier Trick -Snowtrick{% endblock %}

{% block content %}

    <h1 class="text-dark text-center fw-bold">Modidier un trick</h1>

        {% include "/trick/_form.html.twig" %}

{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block album %}{% endblock %}

{% block content %}
    <h1 class="fw-bold text-center" id="Trick"> Tricks</h1>
    <br>
    <p>Le panel de figures faisables en l'air augmente de jour en jour à mesure que les freestyleurs progressent. On peut néanmoins classer les tricks en plusieurs catégories.</p>
    <br>
        <a href="#finish">
            <div class="btn-rond d-flex justify-content-end align-items-end ">
                <img src="{{ asset('assets/images/logoFlecheBas.png') }}" alt="logoFlecheBas" class="logo-btn-rond" >
            </div>
        </a>
    <div class="row row-cols-1  row-cols-md-3 g-3 mb-5">
        {% for trick in tricks %}
            <div class="col">
                <div class="card shadow-sm text-white bg-secondary mb-3">
                    {% if trick.images %}
                        <img src="{{ asset('/upload/tricks/images/'~ trick.firstImage) }}" alt="picture trick">
                    {% endif %}

                    <div class="card-body">

                        <p class="card-text fw-bold text-center text-uppercase">{{ trick.title }}</p>
                        <p class="card-text text-center">{{ trick.slug }}</p>
                        <p class="card-text">{{ trick.description }}</p>

                        <div class="d-flex justify-content-center align-items-center">
                            <div class="row">
                                <div class="col">
                                    <div class="btn-group text-center m-2 text-uppercase ">
                                        <a href="{{ path('app_trick_show', {'slug': trick.slug }) }}"
                                           class="btn btn-sm btn-outline-warning border border-info border-3 text-white fw-bold">{{ trick.title }}
                                        </a>
                                    </div>
                                </div>

                            </div>
                            <div class="btn-group text-center">

                                {% if trick.user == app.user %}
                                    <a href="{{ path('app_trick_edit', {'slug': trick.slug }) }}"
                                       class="btn btn-sm btn-outline-warning border border-info border-3 "><img
                                                src="{{ asset('assets/images/logoEdit.png') }}" height="18px"
                                                alt="Modifier trick"></a>

                                    <a href="{{ path('app_trick_delete', {'slug': trick.slug }) }}"
                                       class="btn btn-sm btn-outline-warning border border-info border-3 "><img
                                                src="{{ asset('assets/images/logoDelete.png') }}" height="18px"
                                                alt="Supprimer trick"></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
    <a href="#Trick" id="finish">
        <div class="btn-rond1 d-flex justify-content-end align-items-end my-4" >
            <img src="{{ asset('assets/images/logoFlecheHaut.png') }}" alt="logoFlecheHaut" class="logo-btn-rond1" >
        </div>
    </a>
{% endblock %}

templates/trick/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Trick -Snowtrick{% endblock %}

{% block album %}{% endblock %}
{% block content %}

        <h1 class="text-dark text-center fw-bold">Nouveau trick</h1>

        {% include "/trick/_form.html.twig" %}

{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{# {% block album %}{% endblock %} #}

{% block content %}
    <section class="container-fluid background-layout-stairs">
        <div class="row justify-content-center">
            <div class="col-md-8 ">
                <div class="card shadow-lg rounded my-5">
                    <div class="jumbotron vh-50 card-img-top">
                        <div class="p-4 p-md-5 mb-2 text-white rounded">
                            <div class="row justify-content-center mb-3">
                                {% if trick.images %}
                                    {% for image in trick.images %}
                                        <img src="{{ asset('/upload/tricks/images/'~ image) }}" alt="picture trick"
                                             class="mb-2">
                                    {% endfor %}
                                    <br>
                                {% endif %}
                                {% if trick.videos %}
                                    {% for video in trick.videos %}
                                        <iframe width="560" height="315" src="https://www.youtube.com/embed/j6uAv1vFP_8"
                                                title="YouTube video player"
                                                frameborder="0"
                                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                allowfullscreen></iframe>
                                    {% endfor %}
                                {% endif %}

                            </div>

                            <div class="d-flex justify-content-end align-items-center mt-3">
                                <div class="btn-group ">
                                    {% if is_granted('ROLE_USER') %}
                                        <a href="{{ path('app_trick_edit', {'slug': trick.slug }) }}"
                                           class="btn btn-sm btn-outline-warning border border-info border-3 text-dark fw-bold"><img
                                                    src="{{ asset('assets/images/logoEdit.png') }}" height="18px"
                                                    alt="Modifier trick"></a>

                                        <a href="{{ path('app_trick_delete', {'slug': trick.slug }) }}"
                                           class="btn btn-sm btn-outline-warning border border-info border-3 text-dark fw-bold"><img
                                                    src="{{ asset('assets/images/logoDelete.png') }}" height="18px"
                                                    alt="Supprimer trick"></a>
                                    {% endif %}
                                    <a href="{{ path('app_trick') }}"
                                       class="btn btn-sm btn-outline-warning border border-info border-3 text-dark fw-bold"><img
                                                src="{{ asset('assets/images/logoReturn.png') }}" height="18px"
                                                alt="Return"></a>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <section class="container-fluid background-layout-stairs mb-2">
        <h5 class="text-center text-uppercase fw-bold">{{ trick.title }}</h5>
        <br>
        <h5 class="text-center text-uppercase fw-bold">{{ trick.category }}</h5>
        <br>
        <h5 class=" text-center text-uppercase fw-bold">{{ trick.user.username }}</h5>
        {% if is_granted('ROLE_USER') %}
        <a href="{{ path('app_comment_new', {'slug': trick.slug }) }}"
           class="btn btn-sm btn-outline-warning border border-info border-3 text-dark fw-bold"><img
                    src="{{ asset('assets/images/logoCommentaire.png') }}" height="18px"
                    alt="Ajouter commentaire" class="m-2">Ajouter un commentaire</a>
        {% endif %}
        <hr>
    </section>
    {% if not is_granted('ROLE_USER') %}
        <h5 class="text-center">Connectez-vous à votre compte afin de laisser un commentaire</h5>

        <div class="d-flex justify-content-center align-items-center mt-3 ">
            <a href="{{ path('app_login') }}"
               class=" btn btn-sm btn-secondary border-3 text-white fw-bold text-center p-3">Connexion </a>
        </div>
    {% endif %}

    {{ render(controller('App\\Controller\\CommentController::getCommentsByTrick', {'trick' : trick.id,'request' : request})) }}

{% endblock %}